name: Terraform
on: [push, pull_request]

jobs:
  check-format:
    strategy:
      matrix:
        paths: [process.env.GITHUB_WORKSPACE, path.join(process.env.GITHUB_WORKSPACE, 'modules', 'imputation-iam'), path.join(process.env.GITHUB_WORKSPACE, 'modules', 'imputation-lb'), path.join(process.env.GITHUB_WORKSPACE, 'modules', 'imputation-security-group-rules'), path.join(process.env.GITHUB_WORKSPACE, 'modules', 'imputation-server')]
    name: Check format
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: terraform fmt
      uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check
      working-directory: ${{ matrix.paths }}