name: Terraform
on: [push, pull_request]

jobs:
  check-format:
    strategy:
      matrix:
        paths: ['/', '/modules/imputation-iam', '/modules/imputation-lb', '/modules/imputation-security-group-rules', '/modules/imputation-server']
    name: Check format
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: terraform fmt
      uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check
      working-directory: ${{ matrix.paths }}